//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "discord_guild_channel")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub channel_id: String,
    pub guild_id: String,
    pub name: String,
    pub position: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::discord_guild::Entity",
        from = "Column::GuildId",
        to = "super::discord_guild::Column::GuildId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    DiscordGuild,
    #[sea_orm(has_many = "super::fleet_category_channel::Entity")]
    FleetCategoryChannel,
}

impl Related<super::discord_guild::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscordGuild.def()
    }
}

impl Related<super::fleet_category_channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FleetCategoryChannel.def()
    }
}

impl Related<super::fleet_category::Entity> for Entity {
    fn to() -> RelationDef {
        super::fleet_category_channel::Relation::FleetCategory.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::fleet_category_channel::Relation::DiscordGuildChannel
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
