//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "fleet_category")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub guild_id: i64,
    pub name: String,
    pub ping_cooldown: Option<i32>,
    pub ping_reminder: Option<i32>,
    pub max_pre_ping: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::discord_guild::Entity",
        from = "Column::GuildId",
        to = "super::discord_guild::Column::GuildId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    DiscordGuild,
}

impl Related<super::discord_guild::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiscordGuild.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
